### ISSUE TITLE
Security risk: `target="_blank"` used without rel on user-submitted links

### ISSUE THREAD

**Issue by coreyward** [smartsupp/smartsupp-plugin-prestashop#1]
When a customer provides a URL via chat, Smartsupp converts it to a link with a `target="_blank"` attribute. No `rel` attribute is provided. This opens the host website up to attack from the target website via `window.location.opener`. See [this excellent demo](https://mathiasbynens.github.io/rel-noopener/) for more information. 

Solution: add `rel="noopener noreferrer"` to the automatically applied attributes on the `<a>` element.

Attn: @dkMorlok

**Comment by krsiakdaniel** [comment]
Hi,  thanks for letting us know. 
We will look into it.
